### ISSUE TITLE
V9 error when generating auditfile

### ISSUE THREAD

**Issue by jvOrsouw** [xoes-oca/l10n_nl_xaf_auditfile_export#1]
@hbrunn 
@astirpe 

I get an error when trying to generate an audit file with your module. Can anyone enlighten me what is wrong with the module or the data?

Traceback (most recent call last):
  ....
  File "/opt/odoo/enterprise/web/controllers/main.py", line 902, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/addons/l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py", line 123, in button_generate
    'XmlAuditfileFinancieel3.2.xsd'))))
  File "xmlschema.pxi", line 102, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:168126)
XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}restriction': The content is not valid. Expected is (annotation?, (simpleType?, (minExclusive | minInclusive | maxExclusive | maxInclusive | totalDigits | fractionDigits | length | minLength | maxLength | enumeration | whiteSpace | pattern)*))., line 639

**Comment by hbrunn** [comment]
look at the line the schema validator is complaining about. Posting the whole file here will get you in trouble with your customer's privacy officer probably, so better be cautious with this. But without seeing the data, it's impossible to help.

**Comment by jvOrsouw** [comment]
@hbrunn didn't see any privacy sensitive info in here, but just to be sure, adjusted the comment. As I cannot generate the data, I have no way of knowing what is missing. Can you give me some insight in what can cause such an error? Perhaps invalid characters that I can search for?
